services:
  icms:
    container_name: 'front'
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '3000:5273'    
    volumes:
      - '.:/app:rw'
      - '/app/node_modules' 
